### ISSUE TITLE
Links to other manual pages

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/maxygen#3]
With some custom syntax. Also, links to other man pages in other packages.

**Comment by hadley** [comment]
It would be nice to have some way to do this automatically so you could just do ``pkg::foo`` and automatically link to foo.

**Comment by gaborcsardi** [comment]
@hadley I like that very much. And ``::foo`` could just link to `foo()` in the current package.

**Comment by gaborcsardi** [comment]
@hadley On a second thought, maybe it is better to have something more specific. I used `pkg::foo` a bunch of times without depending on `pkg`, and then you cannot link (I guess). 

How about ``[pkg::foo]``? Is that too messy?

EDIT: actually, ``pkg::foo`` is fine. You can always to `\code{pkg::foo}` if you do not want to link.

**Comment by gaborcsardi** [comment]
Reopening this, because it would be nice to support the alternative forms of `\link{}`, in a consistent Markdown-line way.

EDIT: here is the R docs for cross-references: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Cross_002dreferences

**Comment by gaborcsardi** [comment]
See also the discussion here: https://github.com/gaborcsardi/maxygen/commit/9e07e1bbe334fe6ed1060f21470bd82c5b123ee6#commitcomment-12538375

**Comment by gaborcsardi** [comment]
OK, so here is the plan:
-  `\code{\link{function}}` becomes `[](::function)`
- `\code{\link[pkg]{foo}}` becomes `[](pkg::function)`
- `\link[=dest]{name}` becomes `[name](::=dest)`
- `\link[pkg:bar]{foo}` becomes `[foo](pkg::bar)` (links to `bar.html` in package `pkg`)

S3/S4 classes:
- "\link[=terms.object]{terms}" becomes `[terms](::=terms.object)`
- "\link[=abc-class]{abc}" becomes `[abc](::=abc-class)`

It is somewhat more clumsy than the clean `pkg::function` notation, but it is more Markdown.

**Comment by hadley** [comment]
What about using pandoc style implicit references? http://pandoc.org/README.html#extension-implicit_header_references

Then I think you could do: `[function]`, `[pkg::function]` etc.

**Comment by gaborcsardi** [comment]
@hadley These look great, but the commonmark specification does not seem to support them: http://spec.commonmark.org/0.22/#inline-link So our parser just ignores them.... :(

**Comment by hadley** [comment]
Isn't the shortcut reference link exactly what we need?

**Comment by gaborcsardi** [comment]
For that you need the "links reference definition" as well, i.e. both parts of 

```
[foo]
...
[foo]: /url "title"
```

Otherwise `[foo]` is just text for the parser. Which is not really optimal for us. I could hack around it, probably, but I am not sure it is worth it.

**Comment by gaborcsardi** [comment]
Oh, wait, you are right, I missed the text at the beginning.

**Comment by gaborcsardi** [comment]
~~Oh, wait, you are right, I missed the text at the beginning.~~

Forget it, it does not work. I tried the parser, actually, and it parses `[foo]` as normal text.

**Comment by gaborcsardi** [comment]
Ok, I might be an idiot, it might work, actually. I promise not to reply here until I find out definitely.... :)

**Comment by gaborcsardi** [comment]
This is fine:

``` r
library(commonmark)> cat(markdown_xml("This is a [link] here.\n\n[link]: http://igraph.org\n"))
#> <?xml version="1.0" encoding="UTF-8"?>
#> <!DOCTYPE CommonMark SYSTEM "CommonMark.dtd">
#> <document>
#>   <paragraph>
#>     <text>This is a </text>
#>     <link destination="http://igraph.org" title="">
#>       <text>link</text>
#>     </link>
#>     <text> here.</text>
#>   </paragraph>
#> </document>
```

This is not:

``` r
cat(markdown_xml("This is not a [link] here.\n\n"))
#> <?xml version="1.0" encoding="UTF-8"?>
#> <!DOCTYPE CommonMark SYSTEM "CommonMark.dtd">
#> <document>
#>   <paragraph>
#>     <text>This is not a </text>
#>     <text>[</text>
#>     <text>link</text>
#>     <text>]</text>
#>     <text> here.</text>
#>   </paragraph>
#> </document>
```

It does parse the links as a separate piece, but it marks it as text, because there is no matching link reference definition.

**Comment by hadley** [comment]
Oh bummer. Is there any way to hook into the parser and supply our own refs?

**Comment by gaborcsardi** [comment]
I'll take a look tomorrow (flying right now), but I doubt it. Markdown does
not really have tags.

Even if possible, I am not sure if we should extend markdown. One of the
points of maxygen is that you can take your existing markdown text and use
it as docs. Or the other way, you can use your docs as README.md. So it
would make sense to use the some standard markdown dialect.

**Comment by hadley** [comment]
It doesn't really feel like an extension to markdown to me - we're just (effectively) presupplying a (large) list of refs that people can use out of the box.

**Comment by gaborcsardi** [comment]
Yeah, I was thinking about that, too. After all, if you copy the roxygen docs to (say) `README.md`, these links do not work anyway.....

As for the implementation, the parser currently puts the `[` ad `]` into separate text nodes in the xml tree, but I am reluctant to rely on that.....

**Comment by hadley** [comment]
Given that we can't make `[pkg::function]` etc work, I think your original proposal sounds good. 

What's the likelihood you could finish this up and do a pull request for roxygen2 by the end of the week? That's when I'm planning of starting the roxygen2 release process.

**Comment by gaborcsardi** [comment]
@hadley Which one is the original? https://github.com/gaborcsardi/maxygen/issues/3#issuecomment-140406708 This?

I will try to do it tomorrow, need to see if I can do this during work hours. :)

**Comment by hadley** [comment]
Yeah, https://github.com/gaborcsardi/maxygen/issues/3#issuecomment-140406708, sorry.

**Comment by gaborcsardi** [comment]
So, I can do this quickly I think. But I am a little worried that it would go out without testing in the wild....

In theory I can just run it through a number of packages and see if anything changes, but I am not sure if I'll have the time for this.

**Comment by hadley** [comment]
Ok, lets leave it for the next release of roxygen2 then.

**Comment by gaborcsardi** [comment]
Yeah, I think that's better. Do you have a plan when that will happen? We can merge it after this release, and then people can try it. 

Btw. I implemented the links in maxygen. I'll put together a PR for roxygen.

Btw.2. we can even get rid of some (all?) other Rd tags if we want to. E.g. we can have

``` markdown
# Arguments
* `foo` Blah-blah.
* `bar` More blah-blah.

# See also
These other functions.
...
```

Essentially we can make some headers to be equivalent to some roxygen tags. But we can discuss this some other place and time.

**Comment by hadley** [comment]
It'll probably be at least 3 months, but more likely 6. But once it's merged and you're happy with it, and we've tested it widely, you can just nag me until I do a new release ;)
