### ISSUE TITLE
Error compiling documentation

### ISSUE THREAD

**Issue by stephlocke** [gaborcsardi/maxygen#5]
Heya Gabor,
Trying to use this in a [new package](https://github.com/stephlocke/RMSFTDP). I've got no functions at the mo, just a package doc file. With the minimum filled in, and using `@title` I get errors when running `maxygen::mocument`

```
> maxygen::macument(".")
Updating RMSFTDP documentation
Loading RMSFTDP
Error in paste(text, collapse = "\n") : 
  argument "rest" is missing, with no default
In addition: There were 16 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: Deprecaated: please use register_tag instead
[...]
16: Deprecaated: please use register_tag instead
```

My package doc file (via `devtools::use_package_doc`) simply contains:

```
#' @title R in the Microsoft Data Platform
#'
#' @name RMSFTDP
#' @docType package
NULL
```

**Am I doing something daft?**

---

```
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMSFTDP_0.0.0.9000

loaded via a namespace (and not attached):
 [1] magrittr_1.5    tools_3.2.4     withr_1.0.1     roxygen2_5.0.1  Rcpp_0.12.4     memoise_1.0.0  
 [7] xml2_0.1.2      stringi_1.0-1   stringr_1.0.0   digest_0.6.9    maxygen_1.0.0   commonmark_0.8 
[13] devtools_1.10.0
```

**Comment by gaborcsardi** [comment]
Hi Steph, maxygen is outdated I think. I did not update it for recent roxygen changes. Sorry about that.

The good news is, maxygen is close to be merged into Roxygen:
https://github.com/klutometis/roxygen/pull/431
Might still change a bit, and I think initially it will be off by default.

**Comment by stephlocke** [comment]
Fab - it'll be awesome for it to be integrated :+1:

**Comment by fernandojunior** [comment]
Hey, how can I install your [PR](https://github.com/klutometis/roxygen/tree/444f5e39362ea956fa2dbbf6260cb1d5eede0828)? Are [these](https://github.com/klutometis/roxygen/blob/444f5e39362ea956fa2dbbf6260cb1d5eede0828/tests/testthat/test-markdown.R) tests running? :)

**Comment by gaborcsardi** [comment]
@fernandojunior See `devtools::install_github()` for installing a pull request locally.

Yes, those tests should work just fine.
